resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/d673b92f2a2d9354d102514d0a0fa74f8248b14a/snapshot.yaml

packages:
  - .

extra-deps:
    # Cardano-ledger dependencies
  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 5241971fe563c90ea82b20af344116d46d672835
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: d673b92f2a2d9354d102514d0a0fa74f8248b14a
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 14f9b09920813447a4060b6810bf17fc4ea35840
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

    # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: 71fb36665338491e92d3ef14c20ae38ad6882c94

  - containers-0.5.11.0
  - ekg-prometheus-adapter-0.1.0.4
  - prometheus-2.1.1
  - pvss-0.2.0
  - time-units-1.0.0
  - libsystemd-journal-1.4.4
  - tasty-hedgehog-1.0.0.1
    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: b2022cf7f5925e486f9e0a31f6f6d02145d5ebda
    subdirs:
      - contra-tracer
      - iohk-monitoring

    # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: ec96c64c665b741c17b4e38f611315bae9b0b054

  - git: https://github.com/joelwilliamson/bimap
    commit: 013a0639c222b3f5572ae20ce364815e5d8f2156

    #Ouroboros-network dependencies

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: f098386495d1e5be64cc4c00557846f554c45cda
    subdirs:
        - io-sim-classes
        - network-mux
        - ouroboros-network
        - ouroboros-consensus
        - typed-protocols
        - typed-protocols-cbor

  # We have to use own fork because of problems with LTS dependencies (QuickCheck 2.12 against 2.13).
  - git: https://github.com/denisshevchenko/ansi-terminal-game
    commit: b0d9aba5684d5fc4681fa12afcf0ac9d4db38747

  - linebreak-1.0.0.3@sha256:3152802008e06f8444d364f6e1047b412e3cb692c1382b1657a425d72a0cfd5f
  - timers-tick-0.4.1.0@sha256:27d345648b8e01fad48adf1dc0e870b19fabb03ccdf3ad0bc5acb57f5da6cb5c

flags:
  iohk-monitoring:
    disable-prometheus: true

nix:
  shell-file: nix/stack-shell.nix
